import Head from "next/head";

export default function Home() {
  return (
    <div className="main">
      <Head>
        <title>SG/SSR Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ul>
        <li>
          <a href="sg">SG</a>
        </li>
        <li>
          <a href="ssr">SSR</a>
        </li>
      </ul>
    </div>
  );
}
