import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <div className="main">
      <Head>
        <title>SG/SSR Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ul>
        <li>
          <Link href='sg'>SG</Link>
        </li>
        <li>
          <Link href='ssr'>SSR</Link>
        </li>
      </ul>
    </div>
  )
}
